---
Name: multisites
After:
  - pageicons-multisites
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\CMS\Controllers\OldPageRedirector:
    class: Fromholdio\ConfiguredMultisites\Extension\MultisitesOldPageRedirector

SilverStripe\CMS\Controllers\CMSMain:
  extensions:
    - Fromholdio\ConfiguredMultisites\Admin\MultisitesCMSMainExtension

# Add path to editor.css per theme, HTMLEditorField will use
# editor.css associated with the theme of the active page.
# SilverStripe\CMS\Controllers\CMSMain:
#   multisites_editor_css_dir:
#     theme-name: 'dist/css'

SilverStripe\Control\Controller:
  extensions:
    - Fromholdio\ConfiguredMultisites\Extension\MultisitesControllerExtension

SilverStripe\Security\Member:
  extensions:
    - Fromholdio\ConfiguredMultisites\Extension\MultisitesMemberExtension

SilverStripe\Admin\ModelAdmin:
  extensions:
    - Fromholdio\ConfiguredMultisites\Admin\MultisitesModelAdminExtension

SilverStripe\CMS\Model\SiteTree:
  create_default_pages: false
  can_be_root: false
  extensions:
    - Fromholdio\ConfiguredMultisites\Extension\MultisitesSiteTreeExtension

Fromholdio\ConfiguredMultisites\Model\Site:
  icon: 'innoweb/silverstripe-page-icons: client/icons/globe.svg'
  can_be_root: true
  hide_ancestor: Fromholdio\ConfiguredMultisites\Model\Site
  defaults:
    Scheme: https

SilverStripe\Reports\Report:
  excluded_reports:
    - SilverStripe\CMS\Reports\EmptyPagesReport
    - SilverStripe\CMS\Reports\RecentlyEditedReport
    - SilverStripe\CMS\Reports\BrokenLinksReport
    - SilverStripe\CMS\Reports\BrokenFilesReport
    - SilverStripe\CMS\Reports\BrokenVirtualPagesReport
    - SilverStripe\CMS\Reports\BrokenRedirectorPagesReport
  extensions:
    - Fromholdio\ConfiguredMultisites\Extension\MultisitesReport

---
Name: multisites-security
After: multisites
Except:
  classexists: 'SilverStripe\LoginForms\EnablerExtension'
---
SilverStripe\Security\Security:
  extensions:
    - Fromholdio\ConfiguredMultisites\Extension\MultisitesSecurityExtension
