---
Name: multisitesmodelascontrollerroutes
After:
  - '*'
  - 'modelascontrollerroutes'
---
SilverStripe\Control\Director:
  rules:
    '': Symbiote\Multisites\Control\MultisitesRootController
    $URLSegment//$Action/$ID/$OtherID: Symbiote\Multisites\Control\MultisitesFrontController
