---
Name: multisitesmodelascontrollerroutes
After:
  - '*'
  - 'modelascontrollerroutes'
---
SilverStripe\Control\Director:
  rules:
    '': Fromholdio\ConfiguredMultisites\Control\MultisitesRootController
    $URLSegment//$Action/$ID/$OtherID: Fromholdio\ConfiguredMultisites\Control\MultisitesFrontController
